name: app-prod
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: apps/webapp/Dockerfile
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
    env_file:
      - apps/webapp/.env
    ports:
      - 3334:3333
    networks:
      - wireguard-proxy-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./apps/webapp/tmp:/app/tmp
      - ./storage/configs:/app/storage/configs

networks:
  wireguard-proxy-network:
    name: wireguard-proxy-network
