name: app-prod
services:
  app:
    restart: always
    build:
      context: apps/webapp
    environment:
      - DB_HOST=
      - HOST=0.0.0.0
      - NODE_ENV=production
    env_file:
      - apps/webapp/.env
    ports:
      - ${PORT}:3333

volumes:
  redis-data:
