/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Configs: () => import('#controllers/configs_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
}
