/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  api: {
    proxy: {
      GetProxies: () => import('#controllers/api/proxy/get_proxies_controller'),
      PickProxy: () => import('#controllers/api/proxy/pick_proxy_controller'),
      TestProxy: () => import('#controllers/api/proxy/test_proxy_controller'),
    },
  },
  config: {
    CreateConfig: () => import('#controllers/config/create_config_controller'),
    DeleteConfig: () => import('#controllers/config/delete_config_controller'),
    ShowConfigs: () => import('#controllers/config/show_configs_controller'),
  },
  proxy: {
    all: {
      RestartAllProxies: () => import('#controllers/proxy/all/restart_all_proxies_controller'),
      StartAllProxies: () => import('#controllers/proxy/all/start_all_proxies_controller'),
      StopAllProxies: () => import('#controllers/proxy/all/stop_all_proxies_controller'),
      TestAllProxies: () => import('#controllers/proxy/all/test_all_proxies_controller'),
    },
    Initializing: () => import('#controllers/proxy/initializing_controller'),
    RestartProxy: () => import('#controllers/proxy/restart_proxy_controller'),
    StartProxy: () => import('#controllers/proxy/start_proxy_controller'),
    StopProxy: () => import('#controllers/proxy/stop_proxy_controller'),
    TestProxy: () => import('#controllers/proxy/test_proxy_controller'),
  },
  Sessions: () => import('#controllers/sessions_controller'),
}
