/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type ConfigTransformer from '#transformers/config_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Config = InferData<ConfigTransformer>
  export namespace Config {
    export type Variants = InferVariants<ConfigTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
