WG_CONFIG_FILE := "../webapp/storage/configs/wg-FR-432.conf"

build:
	@docker build -t protonvpn-proxy .

dev:
	@docker run -d \
	--name protonvpn-proxy-1 \
	--cap-add=NET_ADMIN \
	--device /dev/net/tun:/dev/net/tun \
	--sysctl net.ipv4.ip_forward=1 \
	--sysctl net.ipv6.conf.all.forwarding=1 \
	--sysctl net.ipv4.conf.all.src_valid_mark=1 \
	-v "{{WG_CONFIG_FILE}}:/vpn/wg0.conf:ro" \
	-e PROXY_PORT=3128 \
	-p 3128:3128 \
	protonvpn-proxy

r:
	@echo "Waiting for proxy to be ready..."
	@until curl -sf -x http://localhost:3128 http://httpbin.org/ip > /dev/null; do \
		sleep 1; \
	done
	@curl -x http://localhost:3128 http://httpbin.org/ip#dsadasdsa?dsad=dsada&dsad=dsada
